Integrate node
flojoy-io/nodes pull request #104
Opened 2023-06-13 14:58 UTC by Jin1L

### Description

- [ ] I've included a concise description of what each node does

### Styleguide

- [ ] My node adheres to the [styleguide](https://github.com/flojoy-io/nodes/blob/main/node_styleguide.md) for Flojoy nodes

### Docs

- [ ] I've submitted a PR for a documentation page for the new node(s) that contains usage examples (see docs.flojoy.io)

2023-06-13 21:01 UTC, JeffDotPng requested changes

2023-06-14 17:08 UTC, JeffDotPng commented on TRANSFORMERS/CALCULUS/INTEGRATE/INTEGRATE.py
> +        integrate = np.trapz(np.trapz(input_z, input_x), input_y)
Ideally we would want to return an integrated function like with the ordered pair case, can you do that?

2023-06-19 15:08 UTC, scorinaldi commented on MANIFEST/double_indefinite_integral.manifest.yaml
> +    type: CALCULUS
Why no newline?

2023-06-19 15:09 UTC, scorinaldi commented
hey @JeffDotPng I see you requested changes. Have those changes been addressed? Can we push this PR?

2023-06-19 15:45 UTC, JeffDotPng commented on GENERATORS/SIMULATIONS/SINE/SINE.py
> +        y = Y0 + A * np.sin(2 * np.pi * F * x + PHASE)
I changed this myself because I noticed the output was incorrect when testing the nodes, it was due to the sine node being incorrect all this time.

2023-06-19 16:18 UTC, merged