extractor nodes
flojoy-io/nodes pull request #107
Opened 2023-06-13 20:04 UTC by Jin1L

### Description

- [ ] I've included a concise description of what each node does

### Styleguide

- [ ] My node adheres to the [styleguide](https://github.com/flojoy-io/nodes/blob/main/node_styleguide.md) for Flojoy nodes

### Docs

- [ ] I've submitted a PR for a documentation page for the new node(s) that contains usage examples (see docs.flojoy.io)

2023-06-19 15:12 UTC, scorinaldi commented
Hey @Jin1L -- I added the [WIP] prefix as it looks like this work is still ongoing. Also, would it be possible to break this into two separate PRs as the change is getting quite large?

2023-06-19 17:34 UTC, Jin1L commented
> Hey @Jin1L -- I added the [WIP] prefix as it looks like this work is still ongoing. Also, would it be possible to break this into two separate PRs as the change is getting quite large?

I separated the PR!

2023-06-21 14:53 UTC, scorinaldi requested changes
Hey @Jin1L mostly all looks good. I noted some small changes. Also could you add either a unit test or a screen shot to the PR to verify that the node is acting properly?

2023-06-21 14:53 UTC, scorinaldi commented on MANIFEST/open_image.manifest.yaml
> +        default: ""
Can you add a newline to the end of these yamls?

2023-06-21 15:58 UTC, Jin1L commented
These are the screenshots to the PR.
<img width="1676" alt="Screenshot 2023-06-21 at 11 55 01 AM" src="https://github.com/flojoy-io/nodes/assets/89884098/14cf9ba8-0a62-4bdb-bb59-5d25256add29">
<img width="1672" alt="Screenshot 2023-06-21 at 11 56 35 AM" src="https://github.com/flojoy-io/nodes/assets/89884098/485c84e6-47a7-41d0-aea6-6cada2815bf3">
<img width="804" alt="Screenshot 2023-06-21 at 11 56 45 AM" src="https://github.com/flojoy-io/nodes/assets/89884098/74208a20-11e2-41a8-a2a8-3805f582cef4">

2023-06-21 16:11 UTC, scorinaldi approved these changes
LGTM! thanks!

2023-06-21 16:11 UTC, merged