Read aws s3 node
flojoy-io/nodes pull request #129
Opened 2023-06-19 17:33 UTC by Jin1L

### Description

- [ ] I've included a concise description of what each node does

### Styleguide

- [ ] My node adheres to the [styleguide](https://github.com/flojoy-io/nodes/blob/main/node_styleguide.md) for Flojoy nodes

### Docs

- [ ] I've submitted a PR for a documentation page for the new node(s) that contains usage examples (see docs.flojoy.io)

### Testing

- [ ] This PR includes a unit test ([example here](https://github.com/flojoy-io/nodes/blob/c28808f2d0aec8f116cdb3fccb46c4f5256574e9/TRANSFORMERS/ARITHMETIC/ADD/ADD_test_.py) and/or ideally a screenshot of the node's output on an example app.

2023-06-19 17:46 UTC, Jin1L commented
S3_name refers to the name we use to refer to the access and secret access keys.
The table visualizer is a bit off. However, it displays the data that we retrieved from AWS S3 bucket

![Screenshot 2023-06-19 at 1 42 35 PM](https://github.com/flojoy-io/nodes/assets/89884098/0505d9cd-f238-4e0f-aa14-7cd2bb7f303c)
![Screenshot 2023-06-19 at 1 45 00 PM](https://github.com/flojoy-io/nodes/assets/89884098/076f079d-bf03-4747-9c0c-a56a6b9cd94e)

2023-06-21 15:13 UTC, scorinaldi requested changes
Just a few questions and suggestions!

2023-06-21 15:13 UTC, scorinaldi commented on MANIFEST/read_s3.manifest.yaml
> +        default: ""
Can you add a newline at the end of this yaml please?

2023-06-21 15:13 UTC, scorinaldi commented on EXTRACTORS/FILE/READ_S3/READ_S3.py
> +    s3_name:
Should you rename this to `s3_key_name` for clarity?

2023-06-21 15:13 UTC, scorinaldi commented on EXTRACTORS/FILE/READ_S3/READ_S3.py
> +    except Exception as e:
Why include this try catch block at all if you just wind up re-raising whatever the Exception is?

2023-06-22 14:53 UTC, scorinaldi approved these changes
LGTM

2023-07-05 15:33 UTC, merged